railt.graphql:
    path: /
    methods: [ 'GET', 'POST', 'PATCH', 'PUT' ]
    defaults:
        _controller: Railt\SymfonyBundle\Controller\GraphQLController::handleAction
        schema: '%schemas.default%'
